CREATE SEQUENCE SRC START WITH 500 INCREMENT BY 1 MAXVALUE 999999999 CYCLE NOCACHE;

CREATE TABLE COMPANYMSTR
(
    ID               BIGINT        NOT NULL,
    OID              BIGINT,
    TAXAUTHORITY_ID  BIGINT,
    ADDRESS          CHARACTER(50),
    ZIPCODE          VARCHAR(10),
    TELPHONE         VARCHAR(20),
    TYPE             VARCHAR(20),
    DESC             VARCHAR(500),
    DEFUNCT_IND      CHARACTER(1)  NOT NULL DEFAULT 'N',
    CREATED_BY       VARCHAR(50)   NOT NULL,
    CREATED_DATETIME TIMESTAMP     NOT NULL,
    UPDATED_BY       VARCHAR(50)   NOT NULL,
    UPDATED_DATETIME TIMESTAMP     NOT NULL,
    CONSTRAINT PK6
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE COMPANYMSTR DATA CAPTURE NONE
;
ALTER TABLE COMPANYMSTR NOT VOLATILE
;
ALTER TABLE COMPANYMSTR APPEND OFF
;
ALTER TABLE COMPANYMSTR LOCKSIZE ROW
;
ALTER TABLE COMPANYMSTR DROP RESTRICT ON DROP
;
CREATE TABLE DICT
(
    ID               BIGINT       NOT NULL,
    CODE_CAT         VARCHAR(50)  NOT NULL,
    CODE_KEY         VARCHAR(50)  NOT NULL,
    CODE_VAL         VARCHAR(100) NOT NULL,
    REMARKS          VARCHAR(200),
    SEQ_NO           BIGINT,
    SYS_IND          CHARACTER(1) NOT NULL DEFAULT 'N',
    LANG             CHARACTER(5) NOT NULL DEFAULT 'zh_CN',
    DEFUNCT_IND      CHARACTER(1) NOT NULL DEFAULT 'N',
    CREATED_BY       VARCHAR(50)  NOT NULL,
    CREATED_DATETIME TIMESTAMP    NOT NULL,
    UPDATED_BY       VARCHAR(50)  NOT NULL,
    UPDATED_DATETIME TIMESTAMP    NOT NULL,
    CONSTRAINT PK41
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE DICT DATA CAPTURE NONE
;
ALTER TABLE DICT NOT VOLATILE
;
ALTER TABLE DICT APPEND OFF
;
ALTER TABLE DICT LOCKSIZE ROW
;
ALTER TABLE DICT DROP RESTRICT ON DROP
;
COMMENT ON TABLE DICT IS
'CODE_CAT: ''SAP.HR.CODE.ZZDW'' CODE_KEY: ''1'' CODE_VAL:''集团'' LANG:''zh_CN''、''zh_SG''、''en_US'''
;
CREATE TABLE O
(
    ID          BIGINT       NOT NULL,
    BUKRS       VARCHAR(20),
    STEXT       VARCHAR(20),
    PARENT      BIGINT,
    KOSTL       VARCHAR(20),
    ZHRZZCJID   VARCHAR(20),
    ZHRZZDWID   VARCHAR(20),
    ZHRTXXLID   VARCHAR(20),
    ZHRTXXLMS   VARCHAR(50),
    DEFUNCT_IND CHARACTER(1) NOT NULL DEFAULT 'N',
    CONSTRAINT PK4_1
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE O DATA CAPTURE NONE
;
ALTER TABLE O NOT VOLATILE
;
ALTER TABLE O APPEND OFF
;
ALTER TABLE O LOCKSIZE ROW
;
ALTER TABLE O DROP RESTRICT ON DROP
;
CREATE TABLE P
(
    ID          BIGINT       NOT NULL,
    NACHN       VARCHAR(20),
    NAME2       VARCHAR(20),
    ICNUM       VARCHAR(30),
    EMAIL       VARCHAR(50),
    GESCH       VARCHAR(20),
    TELNO       VARCHAR(20),
    CELNO       VARCHAR(20),
    BUKRS       VARCHAR(20),
    KOSTL       VARCHAR(20),
    DEFUNCT_IND CHARACTER(1) NOT NULL DEFAULT 'N',
    CONSTRAINT PK4_2_3
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE P DATA CAPTURE NONE
;
ALTER TABLE P NOT VOLATILE
;
ALTER TABLE P APPEND OFF
;
ALTER TABLE P LOCKSIZE ROW
;
ALTER TABLE P DROP RESTRICT ON DROP
;
CREATE TABLE POSITION
(
    ID               BIGINT       NOT NULL,
    NAME             VARCHAR(20)  NOT NULL,
    DESC             VARCHAR(200),
    DEFUNCT_IND      CHARACTER(1),
    CREATED_BY       VARCHAR(50),
    CREATED_DATETIME TIMESTAMP,
    UPDATED_BY       VARCHAR(50),
    UPDATED_DATETIME TIMESTAMP,
    CONSTRAINT PK3
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE POSITION DATA CAPTURE NONE
;
ALTER TABLE POSITION NOT VOLATILE
;
ALTER TABLE POSITION APPEND OFF
;
ALTER TABLE POSITION LOCKSIZE ROW
;
ALTER TABLE POSITION DROP RESTRICT ON DROP
;
CREATE TABLE POSITIONORG
(
    ID               BIGINT       NOT NULL,
    POSITION_ID      BIGINT       NOT NULL,
    OID              BIGINT,
    DEFUNCT_IND      CHARACTER(1) NOT NULL DEFAULT 'N',
    CREATED_BY       VARCHAR(50)  NOT NULL,
    CREATED_DATETIME TIMESTAMP    NOT NULL,
    UPDATED_BY       VARCHAR(50)  NOT NULL,
    UPDATED_DATETIME TIMESTAMP    NOT NULL,
    CONSTRAINT PK48
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE POSITIONORG DATA CAPTURE NONE
;
ALTER TABLE POSITIONORG NOT VOLATILE
;
ALTER TABLE POSITIONORG APPEND OFF
;
ALTER TABLE POSITIONORG LOCKSIZE ROW
;
ALTER TABLE POSITIONORG DROP RESTRICT ON DROP
;
CREATE TABLE PS
(
    ID          BIGINT       NOT NULL,
    SID         BIGINT       NOT NULL,
    PID         BIGINT       NOT NULL,
    DEFUNCT_IND CHARACTER(1) NOT NULL DEFAULT 'N',
    CONSTRAINT PK14_1
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE PS DATA CAPTURE NONE
;
ALTER TABLE PS NOT VOLATILE
;
ALTER TABLE PS APPEND OFF
;
ALTER TABLE PS LOCKSIZE ROW
;
ALTER TABLE PS DROP RESTRICT ON DROP
;
COMMENT ON TABLE PS IS
'1、一人可多岗；2、岗位成员可是岗位所属机构外的人员'
;
CREATE TABLE RESOURCEMSTR
(
    ID               BIGINT       NOT NULL,
    NAME             VARCHAR(20)  NOT NULL,
    CODE             VARCHAR(50)  NOT NULL,
    SEQ_NO           VARCHAR(255),
    PARENT_ID        BIGINT,
    TYPE             VARCHAR(50)  NOT NULL,
    URI              VARCHAR(200),
    DEFUNCT_IND      CHARACTER(1) NOT NULL DEFAULT 'N',
    CREATED_BY       VARCHAR(50)  NOT NULL,
    CREATED_DATETIME TIMESTAMP    NOT NULL,
    UPDATED_BY       VARCHAR(50)  NOT NULL,
    UPDATED_DATETIME TIMESTAMP    NOT NULL,
    CONSTRAINT PK17
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE RESOURCEMSTR DATA CAPTURE NONE
;
ALTER TABLE RESOURCEMSTR NOT VOLATILE
;
ALTER TABLE RESOURCEMSTR APPEND OFF
;
ALTER TABLE RESOURCEMSTR LOCKSIZE ROW
;
ALTER TABLE RESOURCEMSTR DROP RESTRICT ON DROP
;
CREATE TABLE ROLEMSTR
(
    ID               BIGINT       NOT NULL,
    NAME             VARCHAR(20)  NOT NULL,
    DESC             VARCHAR(50),
    CODE             VARCHAR(50)  NOT NULL,
    DEFUNCT_IND      CHARACTER(1) NOT NULL DEFAULT 'N',
    CREATED_BY       VARCHAR(50)  NOT NULL,
    CREATED_DATETIME TIMESTAMP    NOT NULL,
    UPDATED_BY       VARCHAR(50)  NOT NULL,
    UPDATED_DATETIME TIMESTAMP    NOT NULL,
    CONSTRAINT PK9
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE ROLEMSTR DATA CAPTURE NONE
;
ALTER TABLE ROLEMSTR NOT VOLATILE
;
ALTER TABLE ROLEMSTR APPEND OFF
;
ALTER TABLE ROLEMSTR LOCKSIZE ROW
;
ALTER TABLE ROLEMSTR DROP RESTRICT ON DROP
;
CREATE TABLE ROLERESOURCE
(
    ID               BIGINT       NOT NULL,
    RESOURCEMSTR_ID  BIGINT,
    ROLEMSTR_ID      BIGINT,
    DEFUNCT_IND      CHARACTER(1),
    CREATED_BY       VARCHAR(50),
    CREATED_DATETIME TIMESTAMP,
    UPDATED_BY       VARCHAR(50),
    UPDATED_DATETIME TIMESTAMP,
    CONSTRAINT PK18
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE ROLERESOURCE DATA CAPTURE NONE
;
ALTER TABLE ROLERESOURCE NOT VOLATILE
;
ALTER TABLE ROLERESOURCE APPEND OFF
;
ALTER TABLE ROLERESOURCE LOCKSIZE ROW
;
ALTER TABLE ROLERESOURCE DROP RESTRICT ON DROP
;
CREATE TABLE S
(
    ID          BIGINT       NOT NULL,
    OID         BIGINT       NOT NULL,
    STEXT       VARCHAR(20),
    KOSTL       VARCHAR(20),
    ZHRTXXLID   VARCHAR(20),
    ZHRTXXLMS   VARCHAR(50),
    DEFUNCT_IND CHARACTER(1) NOT NULL DEFAULT 'N',
    CONSTRAINT PK14_2
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE S DATA CAPTURE NONE
;
ALTER TABLE S NOT VOLATILE
;
ALTER TABLE S APPEND OFF
;
ALTER TABLE S LOCKSIZE ROW
;
ALTER TABLE S DROP RESTRICT ON DROP
;
CREATE TABLE SYNCLOG
(
    ID            BIGINT      NOT NULL,
    VERSION       TIMESTAMP   NOT NULL,
    SYNC_TYPE     VARCHAR(20),
    SYNC_DATETIME TIMESTAMP,
    REMARKS       VARCHAR(50),
    CONSTRAINT PK52
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE SYNCLOG DATA CAPTURE NONE
;
ALTER TABLE SYNCLOG NOT VOLATILE
;
ALTER TABLE SYNCLOG APPEND OFF
;
ALTER TABLE SYNCLOG LOCKSIZE ROW
;
ALTER TABLE SYNCLOG DROP RESTRICT ON DROP
;
CREATE TABLE TAXAUTHORITY
(
    ID                 BIGINT       NOT NULL,
    NAME               VARCHAR(20)  NOT NULL,
    ADDRESS            VARCHAR(100),
    ZIPCODE            VARCHAR(10),
    TELPHONE           VARCHAR(20),
    LEADER_NAME        VARCHAR(20),
    LEADER_POSITION    VARCHAR(20),
    LEADER_TELPHONE    VARCHAR(20),
    CONTACTER_NAME     VARCHAR(20),
    CONTACTER_POSITION VARCHAR(20),
    CONTACTER_TELPHONE VARCHAR(20),
    DEFUNCT_IND        CHARACTER(1),
    CREATED_BY         VARCHAR(50),
    CREATED_DATETIME   TIMESTAMP,
    UPDATED_BY         VARCHAR(50),
    UPDATED_DATETIME   TIMESTAMP,
    CONSTRAINT PK5
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE TAXAUTHORITY DATA CAPTURE NONE
;
ALTER TABLE TAXAUTHORITY NOT VOLATILE
;
ALTER TABLE TAXAUTHORITY APPEND OFF
;
ALTER TABLE TAXAUTHORITY LOCKSIZE ROW
;
ALTER TABLE TAXAUTHORITY DROP RESTRICT ON DROP
;
CREATE TABLE USERCOMPANY
(
    ID               BIGINT       NOT NULL,
    COMPANYMSTR_ID   BIGINT,
    USERMSTR_ID      BIGINT,
    DEFUNCT_IND      CHARACTER(1) NOT NULL DEFAULT 'N',
    CREATED_BY       VARCHAR(50)  NOT NULL,
    CREATED_DATETIME TIMESTAMP    NOT NULL,
    UPDATED_BY       VARCHAR(50)  NOT NULL,
    UPDATED_DATETIME TIMESTAMP    NOT NULL,
    CONSTRAINT PK33
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE USERCOMPANY DATA CAPTURE NONE
;
ALTER TABLE USERCOMPANY NOT VOLATILE
;
ALTER TABLE USERCOMPANY APPEND OFF
;
ALTER TABLE USERCOMPANY LOCKSIZE ROW
;
ALTER TABLE USERCOMPANY DROP RESTRICT ON DROP
;
CREATE TABLE USERMSTR
(
    ID               BIGINT       NOT NULL,
    PID              BIGINT       NOT NULL,
    AD_ACCOUNT       VARCHAR(50),
    PERNR            VARCHAR(20),
    ONBOARD_DATE     TIMESTAMP,
    BIRTHDAY         TIMESTAMP,
    IDENTITY_TYPE    VARCHAR(20),
    IDTENTITY_ID     VARCHAR(50),
    BACKGROUND_INFO  VARCHAR(200),
    DEFUNCT_IND      CHARACTER(1) NOT NULL DEFAULT 'N',
    CREATED_BY       VARCHAR(50)  NOT NULL,
    CREATED_DATETIME TIMESTAMP    NOT NULL,
    UPDATED_BY       VARCHAR(50)  NOT NULL,
    UPDATED_DATETIME TIMESTAMP    NOT NULL,
    CONSTRAINT PK2
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE USERMSTR DATA CAPTURE NONE
;
ALTER TABLE USERMSTR NOT VOLATILE
;
ALTER TABLE USERMSTR APPEND OFF
;
ALTER TABLE USERMSTR LOCKSIZE ROW
;
ALTER TABLE USERMSTR DROP RESTRICT ON DROP
;
CREATE TABLE USERPOSITIONORG
(
    ID               BIGINT        NOT NULL,
    POSITIONORG_ID   BIGINT        NOT NULL,
    USERMSTR_ID      BIGINT        NOT NULL,
    DEFUNCT_IND      CHARACTER(10) NOT NULL DEFAULT 'N',
    CREATED_BY       VARCHAR(50)   NOT NULL,
    CREATED_DATETIME TIMESTAMP     NOT NULL,
    UPDATED_BY       VARCHAR(50)   NOT NULL,
    UPDATED_DATETIME TIMESTAMP     NOT NULL,
    CONSTRAINT PK32
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE USERPOSITIONORG DATA CAPTURE NONE
;
ALTER TABLE USERPOSITIONORG NOT VOLATILE
;
ALTER TABLE USERPOSITIONORG APPEND OFF
;
ALTER TABLE USERPOSITIONORG LOCKSIZE ROW
;
ALTER TABLE USERPOSITIONORG DROP RESTRICT ON DROP
;
CREATE TABLE USERROLE
(
    ID               BIGINT       NOT NULL,
    ROLEMSTR_ID      BIGINT,
    USERMSTR_ID      BIGINT,
    DEFUNCT_IND      CHARACTER(1),
    CREATED_BY       VARCHAR(50),
    CREATED_DATETIME TIMESTAMP,
    UPDATED_BY       VARCHAR(50),
    UPDATED_DATETIME TIMESTAMP,
    CONSTRAINT PK14
    PRIMARY KEY (ID)
)
    IN USERSPACE1
;
ALTER TABLE USERROLE DATA CAPTURE NONE
;
ALTER TABLE USERROLE NOT VOLATILE
;
ALTER TABLE USERROLE APPEND OFF
;
ALTER TABLE USERROLE LOCKSIZE ROW
;
ALTER TABLE USERROLE DROP RESTRICT ON DROP
;
